// DO NOT EDIT: Code generated by matcha from item_deleted.matcha

import gleam/string_builder.{StringBuilder}



pub fn render_builder() -> StringBuilder {
    let builder = string_builder.from_string("")

    builder
}

pub fn render() -> String {
    string_builder.to_string(render_builder())
}
